services:
  email-service:
    build:
      context: ./email-service
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - email-db
      - rabbitmq
    restart: 'unless-stopped'

  spam-service:
    build:
      context: ./spam-service
    depends_on:
      - email-service
      - rabbitmq

  email-db:
    env_file: .env
    image: postgres:15
    ports:
      - '5432:5432'
    restart: 'unless-stopped'

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: 'unless-stopped'
