spring:
  main:
    banner-mode: "off"
  datasource:
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: email
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: email
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
